matrix:
- name: Check all Markdown files
  aspell:
    lang: en
    d: en_GB
  dictionary:
    encoding: utf-8
    wordlists:
    - .markdown_wordlist.txt
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
        comments: true
        attributes:
        - title
        - alt
        ignores:
        - ':matches(code, pre)'
        - 'code'
        - 'pre'
  sources:
  - '**/*.md|!Simulator\ Notes/**|!roughpad/**'
  default_encoding: utf-8

- name: Check all HTML files
  aspell:
    lang: en
    d: en_GB
  dictionary:
    encoding: utf-8
    wordlists:
    - .html_wordlist.txt
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.html:
        comments: true
        attributes:
        - title
        - alt
        ignores:
        - ':matches(code, pre)'
        - 'code'
        - 'pre'
  sources:
  - '**/*.html|!Simulator\ Notes/**|!roughpad/**'
  default_encoding: utf-8

- name: Check all Python files
  aspell:
    lang: en
    d: en_GB
  dictionary:
    encoding: utf-8
    wordlists:
    - .python_wordlist.txt
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.python:
      strings: true
      comments: true
  sources:
  - '**/*.py|!Simulator\ Notes/**|!eagle_sim/**|!roughpad/**'
  default_encoding: utf-8
