# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-checks:
    name: code-quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./src/ --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  testing:
    name: trace-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        echo "PYTHONPATH=./src/megha_sim/" >> $GITHUB_ENV
        echo $PYTHONPATH
#     - name: Test with pytest
#       run: |
#         pytest
    - name: Run on trace dataset
      run: |
        python ./src/runner.py ./traces/input/YH.tr ./simulator_config/config.json 3 2 3 1 1 1
